<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Wed, 20 Jun 2018 23:39:54 +0200
 */

$conf['title'] = 'test';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['fullpath'] = 1;
$conf['dformat'] = '%d.%m/%y %H:%M';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['remote'] = 1;
$conf['remoteuser'] = '';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['proxy']['host'] = '192.168.138.254';
$conf['proxy']['port'] = 8080;
$conf['proxy']['user'] = 'chuprina_iv';
$conf['proxy']['pass'] = '<b>d21ITTRNQ0c=';

// end auto-generated content
