<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Fri, 02 Feb 2018 15:09:12 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
